CREATE TABLE Feed (
    id INTEGER NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    link_code TEXT NOT NULL UNIQUE,
    CONSTRAINT link_code_lower CHECK (link_code = lower(link_code))
) STRICT;

CREATE TABLE SourceFile (
    id INTEGER NOT NULL PRIMARY KEY REFERENCES Feed(id),
    contents BLOB NOT NULL
) STRICT;

CREATE TABLE SourceHTTP (
    id INTEGER NOT NULL PRIMARY KEY REFERENCES Feed(id),
    link TEXT NOT NULL
) STRICT;

CREATE TABLE FilterRemoveCarriageReturn (
    id INTEGER NOT NULL PRIMARY KEY REFERENCES Feed(id)
) STRICT;
